#
# Your Crowdin credentials
#  - The _env versions replace the non-_env versions when using a public repository for security
#  - These environment variables must be defined in the env: section in your GitHub workflow
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path : "."
base_url : "https://api.crowdin.com"

#
# Whether to use the existing file system hierarchy or to flatten it out
#  - true or false, SMF needs this to be true, since our hierarchy isn't flat (agreement.txt vs others)
#
preserve_hierarchy: true

#
# Source files & their translation patterns
#
files: [
 {
  source: "Themes/default/languages/Admin.english.php",
  translation: "%locale%/Admin.%language%.php",
 },
 {
  source: "Themes/default/languages/Agreement.english.php",
  translation: "%locale%/Agreement.%language%.php",
 },
 {
  source: "Themes/default/languages/Alerts.english.php",
  translation: "%locale%/Alerts.%language%.php",
 },
 {
  source: "Themes/default/languages/Drafts.english.php",
  translation: "%locale%/Drafts.%language%.php",
 },
 {
  source: "Themes/default/languages/Editor.english.php",
  translation: "%locale%/Editor.%language%.php",
 },
 {
  source: "Themes/default/languages/EmailTemplates.english.php",
  translation: "%locale%/EmailTemplates.%language%.php",
 },
 {
  source: "Themes/default/languages/Errors.english.php",
  translation: "%locale%/Errors.%language%.php",
 },
 {
  source: "Themes/default/languages/Help.english.php",
  translation: "%locale%/Help.%language%.php",
 },
 {
  source: "Themes/default/languages/index.english.php",
  translation: "%locale%/index.%language%.php",
 },
 {
  source: "Themes/default/languages/Install.english.php",
  translation: "%locale%/Install.%language%.php",
 },
 {
  source: "Themes/default/languages/Login.english.php",
  translation: "%locale%/Login.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageBoards.english.php",
  translation: "%locale%/ManageBoards.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageCalendar.english.php",
  translation: "%locale%/ManageCalendar.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMail.english.php",
  translation: "%locale%/ManageMail.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMaintenance.english.php",
  translation: "%locale%/ManageMaintenance.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageMembers.english.php",
  translation: "%locale%/ManageMembers.%language%.php",
 },
 {
  source: "Themes/default/languages/ManagePaid.english.php",
  translation: "%locale%/ManagePaid.%language%.php",
 },
 {
  source: "Themes/default/languages/ManagePermissions.english.php",
  translation: "%locale%/ManagePermissions.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageScheduledTasks.english.php",
  translation: "%locale%/ManageScheduledTasks.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageSettings.english.php",
  translation: "%locale%/ManageSettings.%language%.php",
 },
 {
  source: "Themes/default/languages/ManageSmileys.english.php",
  translation: "%locale%/ManageSmileys.%language%.php",
 },
 {
  source: "Themes/default/languages/Manual.english.php",
  translation: "%locale%/Manual.%language%.php",
 },
 {
  source: "Themes/default/languages/ModerationCenter.english.php",
  translation: "%locale%/ModerationCenter.%language%.php",
 },
 {
  source: "Themes/default/languages/Modifications.english.php",
  translation: "%locale%/Modifications.%language%.php",
 },
 {
  source: "Themes/default/languages/Modlog.english.php",
  translation: "%locale%/Modlog.%language%.php",
 },
 {
  source: "Themes/default/languages/Packages.english.php",
  translation: "%locale%/Packages.%language%.php",
 },
 {
  source: "Themes/default/languages/PersonalMessage.english.php",
  translation: "%locale%/PersonalMessages.%language%.php",
 },
 {
  source: "Themes/default/languages/Post.english.php",
  translation: "%locale%/Post.%language%.php",
 },
 {
  source: "Themes/default/languages/Profile.english.php",
  translation: "%locale%/Profile.%language%.php",
 },
 {
  source: "Themes/default/languages/Reports.english.php",
  translation: "%locale%/Reports.%language%.php",
 },
 {
  source: "Themes/default/languages/Search.english.php",
  translation: "%locale%/Search.%language%.php",
 },
 {
  source: "Themes/default/languages/Settings.english.php",
  translation: "%locale%/Settings.%language%.php",
 },
 {
  source: "Themes/default/languages/Stats.english.php",
  translation: "%locale%/Stats.%language%.php",
 },
 {
  source: "Themes/default/languages/Themes.english.php",
  translation: "%locale%/Themes.%language%.php",
 },
 {
  source: "Themes/default/languages/Timezones.english.php",
  translation: "%locale%/Timezones.%language%.php",
 },
 {
  source: "Themes/default/languages/Who.english.php",
  translation: "%locale%/Who.%language%.php",
 },
 {
  source: "agreement.txt",
  translation: "agreement.%language%.txt"
 }

]