#
# Your Crowdin credentials
#
"project_id" : ${{ secrets.CI_PROJECT }}
"api_token" : ${{ secrets.CI_API_TOKEN }}
"base_path" : "SMF 2.1 RC4"
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/Themes/default/languages/*.english.php",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/Themes/default/languages/%original_file_name%.%language%.php",

 },
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "agreement.txt",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "agreement.%language%.txt"
 }

]