#
# Your Crowdin credentials
#  - The _env versions replace the non-_env versions when using a public repository for security
#  - These environment variables must be defined in the env: section in your GitHub workflow
#
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path : "."
base_url : "https://api.crowdin.com"

#
# Whether to use the existing file system hierarchy or to flatten it out
#  - true or false, SMF needs this to be true, since our hierarchy isn't flat (agreement.txt vs others)
#
preserve_hierarchy: true

#
# Source files & their translation patterns
#
files: [
 {
  source: "Admin.english.php",
  translation: "Admin.%language%.php",
 },
 {
  source: "Agreement.english.php",
  translation: "Agreement.%language%.php",
 },
 {
  source: "Alerts.english.php",
  translation: "Alerts.%language%.php",
 },
 {
  source: "Drafts.english.php",
  translation: "Drafts.%language%.php",
 },
 {
  source: "Editor.english.php",
  translation: "Editor.%language%.php",
 },
 {
  source: "EmailTemplates.english.php",
  translation: "EmailTemplates.%language%.php",
 },
 {
  source: "Errors.english.php",
  translation: "Errors.%language%.php",
 },
 {
  source: "Help.english.php",
  translation: "Help.%language%.php",
 },
 {
  source: "index.english.php",
  translation: "index.%language%.php",
 },
 {
  source: "Install.english.php",
  translation: "Install.%language%.php",
 },
 {
  source: "Login.english.php",
  translation: "Login.%language%.php",
 },
 {
  source: "ManageBoards.english.php",
  translation: "ManageBoards.%language%.php",
 },
 {
  source: "ManageCalendar.english.php",
  translation: "ManageCalendar.%language%.php",
 },
 {
  source: "ManageMail.english.php",
  translation: "ManageMail.%language%.php",
 },
 {
  source: "ManageMaintenance.english.php",
  translation: "ManageMaintenance.%language%.php",
 },
 {
  source: "ManageMembers.english.php",
  translation: "ManageMembers.%language%.php",
 },
 {
  source: "ManagePaid.english.php",
  translation: "ManagePaid.%language%.php",
 },
 {
  source: "ManagePermissions.english.php",
  translation: "ManagePermissions.%language%.php",
 },
 {
  source: "ManageScheduledTasks.english.php",
  translation: "ManageScheduledTasks.%language%.php",
 },
 {
  source: "ManageSettings.english.php",
  translation: "ManageSettings.%language%.php",
 },
 {
  source: "ManageSmileys.english.php",
  translation: "ManageSmileys.%language%.php",
 },
 {
  source: "Manual.english.php",
  translation: "Manual.%language%.php",
 },
 {
  source: "ModerationCenter.english.php",
  translation: "ModerationCenter.%language%.php",
 },
 {
  source: "Modifications.english.php",
  translation: "Modifications.%language%.php",
 },
 {
  source: "Modlog.english.php",
  translation: "Modlog.%language%.php",
 },
 {
  source: "Packages.english.php",
  translation: "Packages.%language%.php",
 },
 {
  source: "PersonalMessage.english.php",
  translation: "PersonalMessages.%language%.php",
 },
 {
  source: "Post.english.php",
  translation: "Post.%language%.php",
 },
 {
  source: "Profile.english.php",
  translation: "Profile.%language%.php",
 },
 {
  source: "Reports.english.php",
  translation: "Reports.%language%.php",
 },
 {
  source: "Search.english.php",
  translation: "Search.%language%.php",
 },
 {
  source: "Settings.english.php",
  translation: "Settings.%language%.php",
 },
 {
  source: "Stats.english.php",
  translation: "Stats.%language%.php",
 },
 {
  source: "Themes.english.php",
  translation: "Themes.%language%.php",
 },
 {
  source: "Timezones.english.php",
  translation: "Timezones.%language%.php",
 },
 {
  source: "Who.english.php",
  translation: "Who.%language%.php",
 },
 {
  source: "agreement.txt",
  translation: "agreement.%language%.txt"
 }

]