#
# Your Crowdin credentials
#
"project_id" : CROWDIN_PROJECT_ID
"api_token" : GITHUB_TOKEN
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/Themes/default/languages/*.english.php",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/Themes/default/languages/%file_name%.%language%.php",
  "translation_replace": {
      ".english" : ""
  }
 },
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "agreement.txt",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "agreement.%language%.txt"
 }

]