#
# Your Crowdin credentials
#
"project_id" : "441442"
"api_token" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6Ijk2ZDNiNjM3ZmI0MDJjODczZjdiOTdlYWIyNWEyMjJlNmJiYjNmNWQ5YjgyZjUwYjQxOGRmNjM3NGJjMDU3ZDBiNWUwYTgyY2ZkN2Y0OGU5IiwiaWF0IjoxNjEzMzY5NjMwLCJuYmYiOjE2MTMzNjk2MzAsImV4cCI6MTYxNTk1ODAzMCwic3ViIjoiMTQ2MjE2NDQiLCJkb21haW4iOm51bGwsInNjb3BlcyI6WyJwcm9qZWN0Il0sImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.FuRZ6zV4cVxGRn7t7KwBp44RgQeMccRNT7uKDeqNRUwVjsGvJ1lrYlNC_-qZIXbzD1blpeMyGqq1Nh3E_qovUpEec-wChHtkbb_N31qtTiDxe8VCqtMRO7g5ptnP3Pq7LQ4W7E1baeVxO6jmPwWcRD539ifX4tVi-NvjhIiC5kyiB1pEC6KqrJGeTFohi8wpCKbo1FiAGi1Avxl8gMBbDPN4Rcn-CJdHNGfFAp9bMiDWhon41gTBSqa-em24bJErt1gQnYEbWG3DFAH_vdWREVnd908CUlLIDE1Ihog-xfK_0q6LoeYEyOVeAseEMkYQQYz-9oPVPqQer4-a1xvsktrm5zkyW01cm7sjNvxjTrBJSvzhIZSs1jjf6ObqGHtXhXAwYNp725k73SYc9CLZ4ifmlcZ6XCpc3aQZT7oVUbHRhQ8TX2Y6R1jMGi6E746DYaVT__M6ngRIZBDgdvrtLFb_QlZqUgfAPS7JV3aV2wgnqb_0bpapwDZ7xyfqEhKmsDzx1r1H5gv8ZvC9-WOIkALs_N6FM6dJYWS8nJG2pmiNfta3rQ-HHnNHc-tqajn-Llz6ChEHuSpwa1qarHdn1P8-B3Y4ETibuClQJow4oZOmF3TvVkio29l0aIiYI-tY7OAS4lXsldOxDBi4ZyZZZ0CCdUM1Q2zxZyf2gsk7IE8"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true

#
# Files configuration
#
files: [
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "/Themes/default/languages/*.english.php",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "/Themes/default/languages/%original_file_name%.%language%.php",

 },
 {
  #
  # Source files filter
  # e.g. "/resources/en/*.json"
  #
  "source" : "agreement.txt",

  #
  # Where translations will be placed
  # e.g. "/resources/%two_letters_code%/%original_file_name%"
  #
  "translation" : "agreement.%language%.txt"
 }

]