# This is a basic workflow to help you get started with Actions

name: CrowdIn

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 */4 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  crowdin-sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin-action
      # You may pin to the exact commit or the version.
      uses: crowdin/github-action@1.0.18
      with:
        upload_sources: true
        upload_translations: false
        download_translations: true
        # Download translations with pushing to branch
        push_translations: true
        # Commit message for download translations
        commit_message: 'New Crowdin translations by Github Action'
        # To download translations to the specified version branch
        localization_branch_name: 'l10n_crowdin_action'
        # Create pull request after pushing to branch
        create_pull_request: true
        # The title of the new pull request
        pull_request_title: 'New Crowdin translations by Github Action'
        # To add labels for created pull request
        pull_request_labels: 'Language'

        # Authentication
        # Numerical ID of the project
        project_id: ${{ secrets.CI_PROJECT}}
        # Personal access token required for authentication
        token: ${{ secrets.CI_TOKEN}}
